#!/usr/bin/php
<?php

include('settings.inc.php');

$metric  = 'hashrate';
$RRDFILE = $metric . '.rrd';
$RRDPATH = '/mnt/mmc-config/rrd/';
$RRD     = $RRDPATH . $RRDFILE;


if (!file_exists($RRD)) {
        $options = array(
                "--step", "300",
                "--start", "-12 months",
                "DS:" . $metric . ":GAUGE:600:0:U",
                "RRA:AVERAGE:0.5:1:288",
                "RRA:AVERAGE:0.5:12:168",
                "RRA:AVERAGE:0.5:228:365"
        );

        rrd_create($RRD, $options);
        // echo rrd_error();
}

// ############################### Get the data

#require('miner.inc.php');

#$return = miner("summary", "");

#$hashrate = $return['SUMMARY'][0]['MHSav'] * 1000;

    // Veird mismatch between us and the pool.
if (file_exists("/var/log/mg_rate_temp")) {
	$s = file_get_contents("/var/log/mg_rate_temp");
	$s=explode(" ", $s);
} else {
	$s=array(0,0);
}

$hashrate = $s[0];
$hashrate = time() . ':' . $hashrate;

$update = array(
        $hashrate
);

// ###############################
$ret = rrd_update($RRD, $update);
// ###############################
// Generate graph images
function create_graph_hash($output, $start, $title) {
    $RRDPATH = '/mnt/mmc-config/rrd/';
    $options = array(
        "--slope-mode",
        "--start", $start,
        "--title=$title",
        "--vertical-label=Hash per second",
        "--lower=0",
        "DEF:hashrate=" . $RRDPATH . "hashrate.rrd:hashrate:AVERAGE",
        "CDEF:realspeed=hashrate,1000,*",
        "LINE2:realspeed#FF0000"
    );
    $ret = rrd_graph("/tmp/rrd/" . $output, $options);
    if (! $ret) {
        echo "<b>Graph error: </b>".rrd_error()."\n";
    }
}

create_graph_hash("mhsav-hour.png", "-1h", "Last Hour");
create_graph_hash("mhsav-day.png", "-1d", "Last Day");
create_graph_hash("mhsav-week.png", "-1w", "Last Week");
create_graph_hash("mhsav-month.png", "-1m", "Last Month");
create_graph_hash("mhsav-year.png", "-1y", "Last Year");

//Return hashrate
$hashrate;

?>
